# Generated by Django 6.0.3 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
